---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-express-opentelemetry 
  namespace: app-express-opentelemetry
spec:
  selector:
    matchLabels:
      app: app-express-opentelemetry
  replicas: 2 
  template:
    metadata:
      labels:
        app: app-express-opentelemetry
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - loki
                - utility
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - loki
                - utility
            topologyKey: topology.kubernetes.io/zone
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: loki
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: utility
      containers:
      - name: nodejs-app-otlp
        env:
        - name: OTEL_TRACE_URL
          value: http://opentelemetry-collector.opentelemetry.svc.cluster.local:4318/v1/traces
        - name: OTEL_PROVIDER
          value: otlp
        image: serverninja/app-metrics-telemetry-tester:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
