---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  labels:
    app: app-express-opentelemetry
  name: app-express-opentelemetry
  namespace: app-express-opentelemetry
  annotations:
    external-dns.ambassador-service: edge-stack.edge-stack
spec:
  ambassador_id: 
  - default 
  acmeProvider:
    authority: none
  hostname: hello-world.app-express-opentelemetry.trinity.dev.bluescape.io
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 3000
  tls:
    min_tls_version: v1.2
  tlsSecret:
    name: ssl-certificate
