---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    app: app-express-opentelemetry
  name: app-express-opentelemetry
  namespace: app-express-opentelemetry
spec:
  ambassador_id: 
  - default 
  host: hello-world.app-express-opentelemetry.trinity.dev.bluescape.io
  load_balancer:
    cookie:
      name: idToken
    policy: ring_hash
  prefix: /
  resolver: endpoint
  service: app-express-opentelemetry.app-express-opentelemetry:3000
  timeout_ms: 30000
