---
apiVersion: v1
kind: Service
metadata:
  name: app-express-opentelemetry
  namespace: app-express-opentelemetry
spec:
  ports:
  - name: http
    port: 3000 
    protocol: TCP
    targetPort:  http
  selector:
    app: app-express-opentelemetry
  sessionAffinity: None
  type: ClusterIP
